### PR TITLE
Do not set the stack size outside prod

### PR DESCRIPTION
**Pull request by ia0**
MacOS apparently doesn't like it. For some reason Linux doesn't complain (it's probably deleted as dead code before it becomes a problem).

### CODE REVIEW

**Comment by ia0** [comment]
This PR needs testing on MacOS (both to make sure the patches script is portable and that the compilation issue is fixed).

```
git checkout ia0/test_stack
./maintainers/patches apply
./maintainers/patches save
./maintainers/patches restore
git status  # should be clean
cargo test --features=std  # should compile and work
```

To also make sure there is no issue with the MacOS cross-compilation toolchain, we need to test that we can build for prod:

```
./deploy.py --board=nrf52840dk_opensk --opensk --programmer=none
```

**Review by kaczmarczyck — APPROVED** [review]
Approval conditioned on successfully testing on Mac.

Do the scripts work if some module does not have any patches?

**Comment by ia0** [comment]
> Do the scripts work if some module does not have any patches?

I've tested the following scenarios:
- Round-trip (apply, save, restore) when no patch
- Start from no patch, apply, create commit, save
- Start from one patch, apply, delete commit, save

They all work as expected on Linux.

**Comment by dianamin** [comment]
it works on mac. 😄

**Pull request merged**
