### PR TITLE
Do not generate an empty PublicKeyCredentialUserEntity in response to…

### LINKED ISSUE #28: Error while authenticating on Windows 10 when using userVerification
## Expected Behavior
When userVerification set to preferred or required: User enters their PIN and the presses a button. User should then be authenticated.

## Actual Behavior
User enters their PIN and presses a button. User is then stuck on "Touch your authenticator" Windows Hello screen.

See attached Windows logs for errors: [OpenSK UserVerification Error.zip](https://github.com/google/OpenSK/files/4176596/OpenSK.UserVerification.Error.zip)

## Steps to Reproduce the Problem

1. Register new key
1. Authenticate using key with userVerification set to preferred or required

## Specifications

- Platform: Windows 10 (tested on 10.0.18363.592 and 10.0.19041.21)

### LINKED ISSUE #114: Can't recognize "User intent" using "Push button" of nRF52840-MDK USB Dongle
## Expected Behavior

At "registration" and/or "authentication", once user push the button of nRF52840-MDK, browser accept "user intent" for authentication. Then requested process will be done in successfuly.

## Actual Behavior

Windows10 does not recognize user operation putting the button to present "user intent", and authentication request fails due to time-out. It may seems that OpenSK firmware does't recognize pushing dongle's button.

## Steps to Reproduce the Problem

1. Exec ./deploy.py and generate target/*.hex
1. Converting *.hex into "UF2" firmware image by [uf2conv](https://github.com/makerdiary/nrf52840-mdk-usb-dongle)
1. Mount the dongle which has UF2 bootloader DFU mode as mass storage
1. Copy the converted firmware image into mass storage
1. Boot the dongle and confirm VID:PID.
1. Set the dongle as google's security key

## Specifications

- Version: commit 642ee69a9bd6939d4f05c298fcfea101a7dc265a
- Platform: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by gebogebogebo**
Do not generate an empty PublicKeyCredentialUserEntity in response to GetAssertion

Fixes #28 
Fixes #114 

The current version of Windows WebAuthn does not seem to support an empty PublicKeyCredentialUserEntity.

I tested it in the following environments
- windows10 pro 64bit 1909
- Non Resident Key Resister and Authenticate
- https://yubionfido2demo.yubion.com/register_jp.html
- https://fido.identityserver.com
- https://webauthn.io/

Before the modification, the user confirmation button did not respond during the authentication process after the registration process at the above site.
After the modification of the program, the user's authentication was successfully completed by pushing the user's confirmation button after the registration process.

### CODE REVIEW

**Comment by jmichelp** [comment]
Awesome! Thanks a lot for digging into the issue and offered a fix. Much appreciated.
I took the liberty to edit your message in order to correctly link the issues and PR.

@kaczmarczyck will have a look at this.

By the way, very nice article about your investigation: https://qiita.com/gebo/items/612373fc58395b2927e7 👍

**Comment by gebogebogebo** [comment]
Thanks for the comment!
I'm glad you corrected the link to PR correctly.

>By the way, very nice article about your investigation: https://qiita.com/gebo/items/612373fc58395b2927e7 

I'm so glad you even saw the article in Japanese!

**Comment by kaczmarczyck** [comment]
Thank you for looking into this issue and debugging it (even though it's your summer vacation)!

I checked the specification and there is no mention of a special case for empty user IDs. I will create an issue with the specification to check what Microsoft thinks.

I'll add unit-tests in a follow-up PR.

**Comment by kaczmarczyck** [comment]
For anyone with access to the private FIDO Alliance repository:
https://github.com/fido-alliance/fido-2-specs/issues/951

**Comment by gebogebogebo** [comment]
My fix is very small, but thank you for your essential response suggestions!

As mentioned in the Qiita article about this case, I think it's essentially a bug on the browser side, and if the GetAssertion response is unexpected, I think it should be an error on the browser side.

I'm very happy to contribute to this OSS!:smile:

**Pull request merged**
