### PR TITLE
Changed OpenSSL x509 certificate version to v3 

### LINKED ISSUE #455: Batch attestation fails on Yubico's WebAuthn demo
Reported by @bubundas17 in #454 [here](https://github.com/google/OpenSK/issues/454#issuecomment-1091919933).

Tested with `stable` and `develop`, setting
`const USE_BATCH_ATTESTATION: bool = true;`

> Yubico's WebAuthn demo, is no longer accepting the key.
https://demo.yubico.com/webauthn-technical/registration
It says,
`Attestation certificate must use version 3!`

### PR DESCRIPTION
**Pull request by bubundas17**
Fixes #455
still do not know how to add Extension OID according to 
https://www.w3.org/TR/webauthn-1/#packed-attestation-cert-requirements
thanks, @jmichelp and @geofli

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by kaczmarczyck** [comment]
Confirmed to fix #455 !
@jmichelp Since you have been more engaged in this discussion, any objections? :)
@bubundas17 Do you mind signing the [Contributor License Agreement](https://cla.developers.google.com/clas)?

**Comment by bubundas17** [comment]
@kaczmarczyck Signed.

**Review by kaczmarczyck — APPROVED** [review]

**Comment by kaczmarczyck** [comment]
Closing and reopening to trigger workflows.

**Comment by kaczmarczyck** [comment]
Thanks @bubundas17 for your help!

**Comment by bubundas17** [comment]
Welcome. Happy to help :)

**Pull request merged**
