### PR TITLE
Add storage test cases for multi-PIN

### PR DESCRIPTION
**Pull request by hcyang-google**
I was thinking after adding duplicate test cases for multi-PIN, should we remove the original test case as it is totally covered by mult-PIN case. Removing duplicate code is nice, but I think separating out multi-PIN tests also has advantage as multi-PIN isn't a common use case, and might make the original test case's logic look more complicated. WDYT?

### CODE REVIEW

**Comment by hcyang-google** [comment]
@kaczmarczyck ready for review, the second commit might need to be cherry-picked back to develop.

**Review by kaczmarczyck — COMMENTED** [review]
The feature itself looks good.
For fixing the build, maybe we should do it the way develop does? Reduces maintanance and keeps the code closer to develop. We submitted the Cargo.lock files, see
https://github.com/google/OpenSK/pull/550/files

**Comment by hcyang-google** [comment]
Fixed, I cherry-picked the commit in dev.

**Review by kaczmarczyck — APPROVED** [review]

**Comment by kaczmarczyck** [comment]
The binary size report workflow must fail, since it tries to build the code without this PR. Therefore looks good!

**Pull request merged**
