### PR TITLE
Change response in HID_INIT for sync

### PR DESCRIPTION
**Pull request by kaczmarczyck**
Resolves an old TODO in HID to correctly respond to syncs.

- [x] Tests pass

### CODE REVIEW

**Comment by kaczmarczyck** [comment]
Blocking #196

**Comment by jmichelp** [comment]
With this PR, how do we keep track of allocated channels and how do we "expire" them?
Because I could imagine that someone can "hijack" a channel, right?
Nothing seems to prevent someone from allocating a chosen channel which might already be in use.

BTW I think this behavior is legacy from U2F before 1.1 specification.

**Comment by kaczmarczyck** [comment]
This PR doesn't change channel management, or behaviour on a receiving a packet. The only thing that should be different is the output, that changes from empty in some cases to always return a payload.

**Comment by jmichelp** [comment]
It somehow does change it.
By returning a payload, you're implicitly allocating the channel (from the platform point of view). If the sent `cid` is not considered as allocated (i.e. if `self.is_allocated(cid)` is `false`), then we will reject following packets coming on this channel.

**Comment by kaczmarczyck** [comment]
The check for `self.has_valid_channel` is done in both cases, so we only send this response if it comes from a valid channel.
Are there any other concerns about channel hijacking? I don't think this change facilitates them, because sending `INIT` with a channel ID other than broadcast should always just cancel the current sequence, and wouldn't happen by accident.

**Review by jmichelp — APPROVED** [review]

**Pull request merged**
