### PR TITLE
[Do not merge] Test pull-request for issue #169.

### PR DESCRIPTION
**Pull request by gendx**
This is a test for the behavior in #169. This pull request can be removed and #169 marked as fixed once the GitHub checks fail here.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by kaczmarczyck** [comment]
@gendx Is this still uesful to be kept open as a canary?

**Comment by gendx** [comment]
> @gendx Is this still uesful to be kept open as a canary?

Just rebased this pull request to see if the Clippy workflow now fails.

**Comment by jmichelp** [comment]
Anyway, due to recent changes on Github, the workflow for Clippy must be adjusted for it to work properly. It now must be split into 2 workflows: an untrusted one which analyses the PR and produces a structured file with the results and a trusted one which takes this file and creates the annotations.

**Comment by gendx** [comment]
Looks like the current workflow passed instead of denying the lint, so leaving this PR open until #169 is fixed.

**Comment by kaczmarczyck** [comment]
This PR does not work with the current CI, since crypto was excluded from clippy. I verified that CI fails when I add a let-and-return in the opensk library.

**Pull request closed without merging**
