### PR TITLE
cbor: add local copy of LICENSE

### PR DESCRIPTION
**Pull request by daviddrysdale**
Also bump crate version to 0.1.2 in preparation for release.

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by jmichelp — COMMENTED** [review]
Nice catch :)

Should we add a `license-file` entry in the manifest or is it `license` or `license-file`?

**Comment by daviddrysdale** [comment]
`cargo` wants `license` or `license-file` but prefers not both:
```
Verifying sk-cbor v0.1.2 (/home/drysdale/src/OpenSK/libraries/cbor)
warning: only one of `license` or `license-file` is necessary
```

**Review by jmichelp — APPROVED** [review]
Thanks for checking

**Review by kaczmarczyck — APPROVED** [review]
Feel free to publish!

**Pull request merged**
