### PR TITLE
Upgrade setup-python workflows

### PR DESCRIPTION
**Pull request by kaczmarczyck**
Maintenance PR for workflows

### CODE REVIEW

**Comment by jmichelp** [comment]
Seems that `actions/checkout@v2` is also issuing a warning.
Mind bumping it to `v4` in this PR?

**Comment by kaczmarczyck** [comment]
Okay, I bumped all actions to the latest major versions, lets see.

**Review by jmichelp — COMMENTED** [review]
LGTM.
Might be worth noting that cargo-bloat and binary-size-reports are the next 2 workflows which could break. But they require a bit more changes than bumping the version

**Review by jmichelp — APPROVED** [review]

**Comment by kaczmarczyck** [comment]
Yeah, I realized, but wanted to keep this low effort.

**Pull request merged**
