### PR TITLE
Add Feitian USB Dongle

### PR DESCRIPTION
**Pull request by geofli**
Feitian created an hardware dongle according to nRF52840 design, please refer to https://feitiantech.github.io/OpenSK_USB/hardware/ .
There is no need to change anything to Google OpenSK source code, download the OpenSK firmware to Feitian Dongle, and it can work.

### CODE REVIEW

**Comment by geofli** [comment]
@googlebot I signed it!

**Comment by geofli** [comment]
@googlebot I signed it!

**Comment by geofli** [comment]
@googlebot I signed it!

**Comment by geofli** [comment]
@googlebot I fixed it.

**Comment by superskybird** [comment]
@googlebot I fixed it.

**Comment by kaczmarczyck** [comment]
Thank you for your contribution! The case looks great.

Your CLA bot issue might be related to the commit author, that does not match your account on GitHub?

**Comment by geofli** [comment]
@googlebot I consent.

**Comment by kaczmarczyck** [comment]
Can you check the author name and email with i.e.
git log -n 5
and change it accordingly like:
git commit --amend --author="Your Name <email@address.com>"

**Comment by kaczmarczyck** [comment]
I can also offer to resend your PR if this bot is troubling you for unknown reasons.

**Comment by geofli** [comment]
I have changed author name and email.

**Comment by superskybird** [comment]
@googlebot I consent.

**Review by kaczmarczyck — DISMISSED** [review]

**Review by jmichelp — APPROVED** [review]

**Review by kaczmarczyck — APPROVED** [review]

**Comment by barrenechea** [comment]
@geofli so the Feitian is this using the `nrf52840_dongle` as board? (when running the deploy) 🤔

**Comment by jmichelp** [comment]
No, they simply routed the button and the LEDs to the same pins which allows to use the same board definition.

**Pull request merged**
