### PR TITLE
Remove CTAP 2.1 flag

### LINKED ISSUE #128: #cfg in macros
As noted in #127 , we should support `#cfg` inside macro calls, i.e. `cbor_map`.

### PR DESCRIPTION
**Pull request by kaczmarczyck**
In our new develop branch, we drop support for CTAP 2.0 separately from CTAP 2.1.

This is related to #106 and makes #128 much less important since the amount of cfg statements is significantly reduced. (I leave it to @jmichelp if we want to close #128.)

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by kaczmarczyck** [comment]
This will be rebased after #249 is merged.

**Comment by kaczmarczyck** [comment]
Closing this PR to create a new PR against develop.

**Comment by jmichelp** [comment]
All you needed to do was to edit the PR branch :)

**Comment by kaczmarczyck** [comment]
I thought this could be possible, but didn't see where :)

**Comment by jmichelp** [comment]
Click the "edit" button next to the name of the PR. Beside changing the title it also enables the dropdown selectors for the branches. That's how I moved all opened PR yesterday

**Comment by kaczmarczyck** [comment]
Ah thanks. I saw the name change only.

**Comment by kaczmarczyck** [comment]
Oh, actually that doesn't work for me. Maybe I need a higher access tier?

**Pull request closed without merging**
